routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['role','share']], function(){
    
    Auth::routes(); 
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('admin-lang', 'Admin\LanguagesController');
    Route::resource('admin', 'Admin\AdminController');
    Route::resource('admin-langs', 'Admin\LangsController');
    Route::resource('admin-types', 'Admin\TypesController');
    Route::resource('admin-category', 'Admin\CategoriesController');
    Route::resource('admin-propriety', 'Admin\ProprietyController');
    Route::resource('admin-propriety-val', 'Admin\PropertyValController');
    Route::resource('admin-general-settings', 'Admin\GeneralSettingsController');
    Route::resource('admin-blog', 'Admin\BlogController');
    Route::resource('admin-shop', 'Admin\ShopsController');
    Route::resource('admin-shop-members', 'Admin\ShopMembersController');
    Route::resource('image/upload', 'Admin\ImagesUploadController');
    Route::resource('shop_admin', 'Shop\ShopAdminController');
    Route::resource('shop_admin_category', 'Shop\CategoryController');
    Route::resource('shop_admin_type', 'Shop\TypesController');
    Route::resource('shop_admin_property', 'Shop\PropertyController');
    Route::resource('shop_admin_property_val', 'Shop\PropertyValController');
    Route::resource('shop_admin_product', 'Shop\ProductController');

    
    
    Route::get('/getFilterResult/{lang?}', 'PagesController@getFilterResult')->name('getFilterResult');
    Route::get('/wishlistProduct/{lang?}', 'PagesController@wishlistProduct')->name('wishlistProduct');
    Route::get('/wishlist/{lang?}', 'PagesController@wishlist')->name('wishlist');
    Route::get('/product/{id}/{lang?}', 'PagesController@product')->name('product');
    Route::get('/post/{id}/{lang?}', 'PagesController@post')->name('post');
    Route::get('/posts/{lang?}', 'PagesController@posts')->name('posts');
    Route::get('/shops/{lang?}', 'PagesController@shops')->name('shops');
    Route::get('/shop/{id}/{lang?}', 'PagesController@shop')->name('shop');
    Route::get('/type/{id}/{lang?}', 'PagesController@type')->name('type');
    Route::get('/category/{id}/{lang?}', 'PagesController@category')->name('category');
    Route::get('/categories/{lang?}', 'PagesController@categories')->name('categories');
    Route::get('/contact/{lang?}', 'PagesController@contact')->name('contact');
    Route::get('/services/{lang?}', 'PagesController@services')->name('services');
    Route::get('/about/{lang?}', 'PagesController@about')->name('about');
    Route::get('/{lang?}', 'PagesController@wellcome')->name('wellcome');
});

app/Category.php
<?php

namespace App;

use App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',"img"
    ];

    public function getCategoryTrans($langSysName){
       
        if($langSysName == ""){
            $langSysName = config('app.fallback_locale'); 
        }
        $lang=Langs::where('system_name',$langSysName)->first();
        if($lang){
            return $this->hasMany('App\CategoryTrans',"category_id")->where('lang_id',$lang->id)->first();
        }
    }

    public function types(){
        return $this->hasMany('App\Type',"category_id");
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use File;
use App\Type;
use App\Langs;
use App\Category;
use App\Prorpiety;
use App\CategoryTrans;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $langs=Langs::all();
        $categories=Category::all();
        $html = view('admin.general-settings.components.categories.categories-table',compact('categories','langs'))->render();
        return json_encode($html);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $langs=Langs::all();
        $html = view('admin.general-settings.components.categories.categories-modal-add-form',compact('langs'))->render();
        return json_encode($html);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $i=count(Category::all());
        $category=Category::create([
            "name"=>$request['generalName']
        ]);
        foreach($request["names"] as $name){
            CategoryTrans::create([
                "name"=>$name['name'],
                'lang_id'=>$name['id'],
                'category_id'=>$category->id
            ]);
        }

    
        $image = $request['img'];  
        $virgula=strrpos($image,',');
        $str=substr($image, 0,$virgula+1);
        $bara=strrpos($image,'image/');
        $punct=strrpos($image,';base64');
        $extension= substr($str, $bara+6,$punct-$bara-6);
        $image = str_replace('data:image/'.$extension.';base64,', '', $image);
        $image = str_replace(' ', '+', $image);

        $imageName = 'category-image-'.$category->id.'.'.$extension;
 
        File::put('images/categories/'. $imageName, base64_decode($image));

        Category::where('id',$category->id)->update([
            'img' => $imageName
        ]);
        $category=Category::find($category->id);
        $langs=Langs::all();
        $html = view('admin.general-settings.components.categories.category-table-row',compact('langs','category','i'))->render();
        return json_encode($html);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $langs=Langs::all();
        $category=Category::find($id);
        $types=Type::all();
        return view('admin.general-settings.categories.show',compact('langs','category','types'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Category::where('id',$id)->update([
            "name"=>$request['name']
        ]);
        foreach($request["nameTrans"] as $nameTrans){
            $category=CategoryTrans::where('category_id',$id)->where('lang_id',$nameTrans['id'])->first();

            if($category){
                CategoryTrans::where('category_id',$id)->where('lang_id',$nameTrans['id'])->update([
                    "name"=>$nameTrans['name'],
                ]);
            }else{
                CategoryTrans::create([
                    "name"=>$nameTrans['name'],
                    'lang_id'=>$nameTrans['id'],
                    'category_id'=>$id
                ]);
            }
        }

        if($request['img']!=""){
            $image = $request['img'];  
            $virgula=strrpos($image,',');
            $str=substr($image, 0,$virgula+1);
            $bara=strrpos($image,'image/');
            $punct=strrpos($image,';base64');
            $extension= substr($str, $bara+6,$punct-$bara-6);
            $image = str_replace('data:image/'.$extension.';base64,', '', $image);
            $image = str_replace(' ', '+', $image);
    
            $imageName = 'category-image-'.$id.'.'.$extension;
     
            File::put('images/categories/'. $imageName, base64_decode($image));
    
            Category::where('id',$id)->update([
                'img' => $imageName
            ]);
        }
        

        $langs=Langs::all();
        $categories=Category::all();
        $html = view('admin.general-settings.components.categories.categories-table',compact('categories','langs'))->render();
        return json_encode($html);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       Category::where('id',$id)->delete();
       return 1;
    }
}

app/Http/Controllers/Shop/CategoryController.php
<?php

namespace App\Http\Controllers\Shop;

use Auth;
use App\Category;
use App\ShopMemebers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $shopMember = ShopMemebers::where('email',Auth::user()->email)->first();
        if(!$shopMember){ Auth::logout(); }
        $categories = Category::all();
        $categ = Category::find($id);
        $products = $shopMember->shop->products($id);
        return view('shop-admin.categories.show',compact('categories','categ','shopMember','products'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/general-settings/components/categories/categories-modal-add-form.blade.php
<div>
    <form id="add-category-form" data-url="{{route('admin-category.store')}}" method="post">
        <div class="row mb-2 justify-content-center">
            <div class="col-md-10">
                <input type="text" value="" id="add-category-general-name" placeholder="Category general name"
                    class="form-control" required>
            </div>
        </div>
        @foreach ($langs as $lang)
        <div class="row mb-2 justify-content-center">
            <div class="col-md-10">
                <input data-lang-id="{{$lang->id}}" type="text" placeholder="Category name in {{$lang->name}}"
                    data-lang="" class="add-category-name form-control" required>
            </div>
        </div>
        @endforeach
        <div class="row mb-2 justify-content-center">
            <div class="col-md-10">
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="add-input-category-img" required>
                        <label class="custom-file-label" for="add-input-category-img">Category image</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="my-2 row justify-content-center">
            <div class="col-md-10">
                <img style="width:100%;" id="category-croped-image" src="" alt="">
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-10">
                <button type="submit" class="btn btn-success btn-block">Add</button>
            </div>
        </div>
    </form>
</div>

resources/views/admin/general-settings/components/categories/categories-table.blade.php
<table class="table">
    <thead class="thead-light">
        <tr>
            <th colspan="{{count($langs)+6}}" class="p-0" scope="col">
                <button data-url="{{route('admin-category.create')}}" class="btn btn-primary btn-block"
                    data-toggle="modal" data-target="#add-category">
                    <i class="fas fa-plus"></i>
                </button>

                <div class="modal fade" id="add-category" tabindex="-1" role="dialog"
                    aria-labelledby="add-category-label" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="add-category-label">Add category</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div id="add-modal-body" class="modal-body">
                            </div>
                        </div>
                    </div>
                </div>
            </th>
        </tr>
        <tr>
            <th class="w-5 text-center" scope="col">#</th>
            <th class="w-5 text-center" scope="col">Image</th>
            <th class="w-15 text-center" scope="col">Category link</th>
            <th class="w-20 text-center" scope="col">General name</th>
            @foreach ($langs as $lang)
            <th class="text-center" scope="col">{{$lang->name}}</th>
            @endforeach
            <th class="w-5 text-center" scope="col">Edit</th>
            <th class="w-5 text-center" scope="col">Delete</th>
        </tr>
    </thead>
    <tbody id="gs-table-tbody">
        @foreach ($categories as $i=>$category)
        <tr class="category-table-row-{{$category->id}}">
            <th class="text-center" scope="row">{{$i+1}}</th>
            <th class="text-center pt-1" scope="row">
                <img style="width:100%;" src="/images/categories/{{$category->img}}" alt="">
            </th>
            <td class="text-center">
                <a href="{{route('admin-category.show',$category->id)}}">
                    <i class="fas fa-link"></i>
                </a>
            </td>
            <td class="text-center">{{$category->name}}</td>
            @foreach ($langs as $lang)
            <td class="text-center" scope="col">{{$category->getCategoryTrans($lang->system_name)['name']}}</td>
            @endforeach
            <td class="text-center">
                <i class="fas fa-edit text-success" data-toggle="modal"
                    data-target="#edit-category-gs-modal-{{$category->id}}"></i>

                <div class="modal fade" id="edit-category-gs-modal-{{$category->id}}" tabindex="-1" role="dialog"
                    aria-labelledby="edit-category-gs-modal-{{$category->id}}-label" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="edit-category-gs-modal-{{$category->id}}-label">Edit
                                    category</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form data-url="{{route('admin-category.update',$category->id)}}"
                                    data-category-id="{{$category->id}}" class="edit-category-form">
                                    <div class="row justify-content-center">
                                        <div class="col-md-10">
                                            <input type="text" class="form-control"
                                                id="edit-category-name-{{$category->id}}" value="{{$category->name}}"
                                                required>
                                        </div>
                                    </div>
                                    @foreach ($langs as $lang)
                                    <div class="row mt-2 justify-content-center">
                                        <div class="col-md-10">
                                            <input placeholder="{{$lang->name}}" data-lang-id="{{$lang->id}}"
                                                type="text"
                                                class="form-control edit-category-name-trans-{{$category->id}}"
                                                value="{{$category->getCategoryTrans($lang->system_name)['name']}}" required>
                                        </div>
                                    </div>
                                    @endforeach
                                    <div class="row my-2 justify-content-center">
                                        <div class="col-md-10">
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" class="edit-input-category-img custom-file-input" data-cat-id="{{$category->id}}">
                                                    <label class="custom-file-label" for="add-input-category-img">Category image</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="my-2 row justify-content-center">
                                        <div class="col-md-10">
                                            <img style="width:100%;" id="edit-category-croped-image-{{$category->id}}" src="" alt="">
                                        </div>
                                    </div>
                                    <div class="row mt-2 justify-content-center">
                                        <div class="col-md-10">
                                            <button type="submit" class="btn-block btn btn-success">Save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td class="text-center">
                <i class="fas fa-trash-alt text-danger" data-toggle="modal" data-target="#delete-category-modal"></i>

                <div class="modal fade" id="delete-category-modal" tabindex="-1" role="dialog"
                    aria-labelledby="delete-category-modal-label" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-center" id="delete-category-modal-label">Are you sure that
                                    you want to delete this category ?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="row justify-content-center">
                                    <div class="col-md-5">
                                        <button type="button" data-dismiss="modal" aria-label="Close"
                                            class="btn btn-block btn-success">Cancel</button>
                                    </div>
                                    <div class="col-md-5">
                                        <button data-id="{{$category->id}}"
                                            data-url="{{route('admin-category.destroy',$category->id)}}"
                                            class="delete-category-btn btn btn-block btn-danger">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/admin/general-settings/components/categories/category-table-row.blade.php
<tr class="category-table-row-{{$category->id}}">
    <th class="text-center" scope="row">{{$i+1}}</th>
    <th class="text-center pt-1" scope="row">
        <img style="width:100%;" src="/images/categories/{{$category->img}}" alt="">
    </th>
    <td class="text-center">
        <a href="{{route('admin-category.show',$category->id)}}">
            <i class="fas fa-link"></i>
        </a>
    </td>
    <td class="text-center">{{$category->name}}</td>
    @foreach ($langs as $lang)
    <td class="text-center" scope="col">{{$category->getCategoryTrans($lang->system_name)['name']}}</td>
    @endforeach
    <td class="text-center">
        <i class="fas fa-edit text-success" data-toggle="modal"
            data-target="#edit-category-gs-modal-{{$category->id}}"></i>

        <div class="modal fade" id="edit-category-gs-modal-{{$category->id}}" tabindex="-1" role="dialog"
            aria-labelledby="edit-category-gs-modal-{{$category->id}}-label" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="edit-category-gs-modal-{{$category->id}}-label">Edit
                            category</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form data-url="{{route('admin-category.update',$category->id)}}"
                            data-category-id="{{$category->id}}" class="edit-category-form">
                            <div class="row justify-content-center">
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="edit-category-name-{{$category->id}}"
                                        value="{{$category->name}}" required>
                                </div>
                            </div>
                            @foreach ($langs as $lang)
                            <div class="row mt-2 justify-content-center">
                                <div class="col-md-10">
                                    <input placeholder="{{$lang->name}}" data-lang-id="{{$lang->id}}" type="text"
                                        class="form-control edit-category-name-trans-{{$category->id}}"
                                        value="{{$category->getCategoryTrans($lang->system_name)['name']}}" required>
                                </div>
                            </div>
                            @endforeach
                            <div class="row my-2 justify-content-center">
                                <div class="col-md-10">
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="edit-input-category-img custom-file-input"
                                                data-cat-id="{{$category->id}}">
                                            <label class="custom-file-label" for="add-input-category-img">Category
                                                image</label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="my-2 row justify-content-center">
                                <div class="col-md-10">
                                    <img style="width:100%;" id="edit-category-croped-image-{{$category->id}}" src=""
                                        alt="">
                                </div>
                            </div>
                            <div class="row mt-2 justify-content-center">
                                <div class="col-md-10">
                                    <button type="submit" class="btn-block btn btn-success">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </td>
    <td class="text-center">
        <i class="fas fa-trash-alt text-danger" data-toggle="modal" data-target="#delete-category-modal"></i>

        <div class="modal fade" id="delete-category-modal" tabindex="-1" role="dialog"
            aria-labelledby="delete-category-modal-label" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-center" id="delete-category-modal-label">Are you sure that
                            you want to delete this category ?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row justify-content-center">
                            <div class="col-md-5">
                                <button type="button" data-dismiss="modal" aria-label="Close"
                                    class="btn btn-block btn-success">Cancel</button>
                            </div>
                            <div class="col-md-5">
                                <button data-id="{{$category->id}}"
                                    data-url="{{route('admin-category.destroy',$category->id)}}"
                                    class="delete-category-btn btn btn-block btn-danger">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </td>
</tr>