routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['role','share']], function(){
    
    Auth::routes(); 
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('admin-lang', 'Admin\LanguagesController');
    Route::resource('admin', 'Admin\AdminController');
    Route::resource('admin-langs', 'Admin\LangsController');
    Route::resource('admin-types', 'Admin\TypesController');
    Route::resource('admin-category', 'Admin\CategoriesController');
    Route::resource('admin-propriety', 'Admin\ProprietyController');
    Route::resource('admin-propriety-val', 'Admin\PropertyValController');
    Route::resource('admin-general-settings', 'Admin\GeneralSettingsController');
    Route::resource('admin-blog', 'Admin\BlogController');
    Route::resource('admin-shop', 'Admin\ShopsController');
    Route::resource('admin-shop-members', 'Admin\ShopMembersController');
    Route::resource('image/upload', 'Admin\ImagesUploadController');
    Route::resource('shop_admin', 'Shop\ShopAdminController');
    Route::resource('shop_admin_category', 'Shop\CategoryController');
    Route::resource('shop_admin_type', 'Shop\TypesController');
    Route::resource('shop_admin_property', 'Shop\PropertyController');
    Route::resource('shop_admin_property_val', 'Shop\PropertyValController');
    Route::resource('shop_admin_product', 'Shop\ProductController');

    
    
    Route::get('/getFilterResult/{lang?}', 'PagesController@getFilterResult')->name('getFilterResult');
    Route::get('/wishlistProduct/{lang?}', 'PagesController@wishlistProduct')->name('wishlistProduct');
    Route::get('/wishlist/{lang?}', 'PagesController@wishlist')->name('wishlist');
    Route::get('/product/{id}/{lang?}', 'PagesController@product')->name('product');
    Route::get('/post/{id}/{lang?}', 'PagesController@post')->name('post');
    Route::get('/posts/{lang?}', 'PagesController@posts')->name('posts');
    Route::get('/shops/{lang?}', 'PagesController@shops')->name('shops');
    Route::get('/shop/{id}/{lang?}', 'PagesController@shop')->name('shop');
    Route::get('/type/{id}/{lang?}', 'PagesController@type')->name('type');
    Route::get('/category/{id}/{lang?}', 'PagesController@category')->name('category');
    Route::get('/categories/{lang?}', 'PagesController@categories')->name('categories');
    Route::get('/contact/{lang?}', 'PagesController@contact')->name('contact');
    Route::get('/services/{lang?}', 'PagesController@services')->name('services');
    Route::get('/about/{lang?}', 'PagesController@about')->name('about');
    Route::get('/{lang?}', 'PagesController@wellcome')->name('wellcome');
});

app/Category.php
<?php

namespace App;

use App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',"img"
    ];

    public function getCategoryTrans($langSysName){
       
        if($langSysName == ""){
            $langSysName = config('app.fallback_locale'); 
        }
        $lang=Langs::where('system_name',$langSysName)->first();
        if($lang){
            return $this->hasMany('App\CategoryTrans',"category_id")->where('lang_id',$lang->id)->first();
        }
    }

    public function types(){
        return $this->hasMany('App\Type',"category_id");
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use File;
use App\Type;
use App\Langs;
use App\Category;
use App\Prorpiety;
use App\CategoryTrans;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $langs=Langs::all();
        $categories=Category::all();
        $html = view('admin.general-settings.components.categories.categories-table',compact('categories','langs'))->render();
        return json_encode($html);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $langs=Langs::all();
        $html = view('admin.general-settings.components.categories.categories-modal-add-form',compact('langs'))->render();
        return json_encode($html);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $i=count(Category::all());
        $category=Category::create([
            "name"=>$request['generalName']
        ]);
        foreach($request["names"] as $name){
            CategoryTrans::create([
                "name"=>$name['name'],
                'lang_id'=>$name['id'],
                'category_id'=>$category->id
            ]);
        }

    
        $image = $request['img'];  
        $virgula=strrpos($image,',');
        $str=substr($image, 0,$virgula+1);
        $bara=strrpos($image,'image/');
        $punct=strrpos($image,';base64');
        $extension= substr($str, $bara+6,$punct-$bara-6);
        $image = str_replace('data:image/'.$extension.';base64,', '', $image);
        $image = str_replace(' ', '+', $image);

        $imageName = 'category-image-'.$category->id.'.'.$extension;
 
        File::put('images/categories/'. $imageName, base64_decode($image));

        Category::where('id',$category->id)->update([
            'img' => $imageName
        ]);
        $category=Category::find($category->id);
        $langs=Langs::all();
        $html = view('admin.general-settings.components.categories.category-table-row',compact('langs','category','i'))->render();
        return json_encode($html);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $langs=Langs::all();
        $category=Category::find($id);
        $types=Type::all();
        return view('admin.general-settings.categories.show',compact('langs','category','types'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Category::where('id',$id)->update([
            "name"=>$request['name']
        ]);
        foreach($request["nameTrans"] as $nameTrans){
            $category=CategoryTrans::where('category_id',$id)->where('lang_id',$nameTrans['id'])->first();

            if($category){
                CategoryTrans::where('category_id',$id)->where('lang_id',$nameTrans['id'])->update([
                    "name"=>$nameTrans['name'],
                ]);
            }else{
                CategoryTrans::create([
                    "name"=>$nameTrans['name'],
                    'lang_id'=>$nameTrans['id'],
                    'category_id'=>$id
                ]);
            }
        }

        if($request['img']!=""){
            $image = $request['img'];  
            $virgula=strrpos($image,',');
            $str=substr($image, 0,$virgula+1);
            $bara=strrpos($image,'image/');
            $punct=strrpos($image,';base64');
            $extension= substr($str, $bara+6,$punct-$bara-6);
            $image = str_replace('data:image/'.$extension.';base64,', '', $image);
            $image = str_replace(' ', '+', $image);
    
            $imageName = 'category-image-'.$id.'.'.$extension;
     
            File::put('images/categories/'. $imageName, base64_decode($image));
    
            Category::where('id',$id)->update([
                'img' => $imageName
            ]);
        }
        

        $langs=Langs::all();
        $categories=Category::all();
        $html = view('admin.general-settings.components.categories.categories-table',compact('categories','langs'))->render();
        return json_encode($html);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       Category::where('id',$id)->delete();
       return 1;
    }
}

app/Http/Controllers/Shop/CategoryController.php
<?php

namespace App\Http\Controllers\Shop;

use Auth;
use App\Category;
use App\ShopMemebers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $shopMember = ShopMemebers::where('email',Auth::user()->email)->first();
        if(!$shopMember){ Auth::logout(); }
        $categories = Category::all();
        $categ = Category::find($id);
        $products = $shopMember->shop->products($id);
        return view('shop-admin.categories.show',compact('categories','categ','shopMember','products'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Shop/ShopAdminController.php
<?php

namespace App\Http\Controllers\Shop;

use Auth;
use App\Shop;
use App\Category;
use App\ShopMemebers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ShopAdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $shopMember = ShopMemebers::where('email',Auth::user()->email)->first();
        if(!$shopMember){ Auth::logout(); }
        $categories = Category::all();
        return view('shop-admin.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/shop-admin/categories/show.blade.php
@extends('layouts.'.Auth::user()->userRole->role->default_page)

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-6">
                <img style="width:100%;" src="/images/categories/{{$categ->img}}" alt="">
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <h2>{{$categ->name}}</h2>
                    </div>
                </div>

                @foreach ($langs as $lang)
                <div class="row">
                    <div class="col-md-2">
                        <span class="monospaced">{{$lang->name}}</span>
                    </div>
                    <div class="col-md-10">
                        <p>
                            {{$categ->getCategoryTrans($lang->id)['name']}}
                        </p>
                    </div>
                </div>
                @endforeach

            </div>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12">
                <button class="btn btn-primary btn-block" data-toggle="modal" data-target="#add-product-modal">
                    <i class="fas fa-plus"></i>
                </button>

                <div class="modal fade" id="add-product-modal" tabindex="-1" role="dialog"
                    aria-labelledby="add-product-modal-label" aria-hidden="true">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="add-product-modal-label">Add product</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form data-shop-id="{{$shopMember->shop->id}}"
                                    data-url="{{route("shop_admin_product.store")}}" id="add-product-form">
                                    @foreach ($langs as $i=>$lang)
                                    <div data-lang-id="{{$lang->id}}"
                                        class="add-product-product-name-and-descript-group row mb-2 justify-content-center">
                                        <div class="col-md-10">
                                            <input type="text" placeholder="Product name in {{$lang->name}}"
                                                id="add-product-product-name-{{$lang->id}}" class="form-control">
                                        </div>
                                    </div>
                                    <div class="row mb-2 justify-content-center">
                                        <div class="col-md-10">
                                            <textarea class="add-product-product-description-{{$lang->id}} form-control"
                                                placeholder="Product description in {{$lang->name}}"
                                                id="editor-{{$i}}"></textarea>
                                        </div>
                                    </div>
                                    @endforeach
                                    <hr>
                                    <div class="row mb-2 justify-content-center">
                                        <div class="col-md-10">
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" class="custom-file-input" name="images[]"
                                                        id="input-product-images"
                                                        aria-describedby="input-product-images-addon-1" multiple>
                                                    <label class="custom-file-label" for="input-product-images">Choose
                                                        images</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mb-2 justify-content-center">
                                        <div id="image-input-preview-galery" class="col-md-10"></div>
                                    </div>
                                    <hr>
                                    <div id="product-types-row" class="row mb-2 justify-content-center">
                                        <div class="col-md-10">
                                            <select class="form-control" id="add-product-select-type">
                                                <option value="" selected disabled>Select type</option>
                                                @foreach ($categ->types as $type)
                                                <option data-url="{{route('shop_admin_type.show',$type->id)}}"
                                                    value="{{$type->id}}">{{$type->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <hr>
                                    <div class="row mb-2 justify-content-center">
                                        <div class="col-md-10">
                                            <input type="text" id="add-product-product-base-price" placeholder="Price"
                                                class="form-control">
                                        </div>
                                    </div>
                                    <div class="row justify-content-center">
                                        <div class="col-md-10">
                                            <button class="btn btn-success btn-block">Add</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            @foreach ($products as $product)
            <div class="mt-4 col-lg-4">
                <div class="product-grid6">
                    <div class="product-image6">
                        <a href="#">
                            <img class="pic-1" src="/images/products/{{$product->images[0]->img}}">
                        </a>
                    </div>
                    <div class="product-content">
                        <h3 class="title"><a href="#">{{$product->prodTrans(Auth::user()::getLang()->system_name)['name']}}</a></h3>
                        <div class="price">{{$product->price}} lei</div>
                    </div>
                    <ul class="social">
                        <li><a href="{{route('shop_admin_product.show',$product->id)}}"><i class="fa fa-search"></i></a></li>
                        <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <button class="btn btn-success btn-block">
                            <i class="fas fa-pencil-alt mr-2"></i>Edit
                        </button>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-danger btn-block" data-toggle="modal" data-target="#delete-product-modal">
                            <i class="fas fa-trash-alt mr-2"></i>Delete
                        </button>

                        <div class="modal fade" id="delete-product-modal" tabindex="-1" role="dialog"
                            aria-labelledby="delete-product-modalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="delete-product-modalLabel">Are you sure that you want to delete this product?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                       <div class="row justify-content-center">
                                            <div class="col-md-5">
                                                <button type="button" class="btn btn-success btn-block" data-dismiss="modal">No</button>
                                            </div>
                                           <div class="col-md-5">
                                               <button data-url="{{route('shop_admin_product.destroy',$product->id)}}" class="delete-product-confirm-btn btn btn-danger btn-block">Yes</button>
                                           </div>
                                       </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @endforeach
        </div>

    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-dark text-center">Types</h3>
            </div>
        </div>
        <hr>
        <div class="ml-3 row">
            @foreach ($categ->types as $type)
            <div class="col-md-12">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        {{$type->name}}
                    </label>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>
@endsection