routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['role','share']], function(){
    
    Auth::routes(); 
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('admin-lang', 'Admin\LanguagesController');
    Route::resource('admin', 'Admin\AdminController');
    Route::resource('admin-langs', 'Admin\LangsController');
    Route::resource('admin-types', 'Admin\TypesController');
    Route::resource('admin-category', 'Admin\CategoriesController');
    Route::resource('admin-propriety', 'Admin\ProprietyController');
    Route::resource('admin-propriety-val', 'Admin\PropertyValController');
    Route::resource('admin-general-settings', 'Admin\GeneralSettingsController');
    Route::resource('admin-blog', 'Admin\BlogController');
    Route::resource('admin-shop', 'Admin\ShopsController');
    Route::resource('admin-shop-members', 'Admin\ShopMembersController');
    Route::resource('image/upload', 'Admin\ImagesUploadController');
    Route::resource('shop_admin', 'Shop\ShopAdminController');
    Route::resource('shop_admin_category', 'Shop\CategoryController');
    Route::resource('shop_admin_type', 'Shop\TypesController');
    Route::resource('shop_admin_property', 'Shop\PropertyController');
    Route::resource('shop_admin_property_val', 'Shop\PropertyValController');
    Route::resource('shop_admin_product', 'Shop\ProductController');

    
    
    Route::get('/getFilterResult/{lang?}', 'PagesController@getFilterResult')->name('getFilterResult');
    Route::get('/wishlistProduct/{lang?}', 'PagesController@wishlistProduct')->name('wishlistProduct');
    Route::get('/wishlist/{lang?}', 'PagesController@wishlist')->name('wishlist');
    Route::get('/product/{id}/{lang?}', 'PagesController@product')->name('product');
    Route::get('/post/{id}/{lang?}', 'PagesController@post')->name('post');
    Route::get('/posts/{lang?}', 'PagesController@posts')->name('posts');
    Route::get('/shops/{lang?}', 'PagesController@shops')->name('shops');
    Route::get('/shop/{id}/{lang?}', 'PagesController@shop')->name('shop');
    Route::get('/type/{id}/{lang?}', 'PagesController@type')->name('type');
    Route::get('/category/{id}/{lang?}', 'PagesController@category')->name('category');
    Route::get('/categories/{lang?}', 'PagesController@categories')->name('categories');
    Route::get('/contact/{lang?}', 'PagesController@contact')->name('contact');
    Route::get('/services/{lang?}', 'PagesController@services')->name('services');
    Route::get('/about/{lang?}', 'PagesController@about')->name('about');
    Route::get('/{lang?}', 'PagesController@wellcome')->name('wellcome');
});

resources/views/admin/shop-management/edit.blade.php
@extends('layouts.admin')

@section('content')
<form id="edit-shop-form" data-url="{{route("admin-shop.update",$shop->id)}}">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <input id="shop-name" value="{{$shop->name}}" placeholder="Shop name" type="text" class="form-control" required>
        </div>
    </div>
    <div class="mt-2 row justify-content-center">
        <div class="col-md-10">
            <input id="shop-email" value="{{$shop->email}}" placeholder="Shop email" type="email" class="form-control" required>
        </div>
    </div>
    <div class="mt-2 row justify-content-center">
        <div class="col-md-10">
            <input id="shop-phone" value="{{$shop->phone}}" placeholder="Shop phone" type="text" class="form-control" required>
        </div>
    </div>
    <div class="mt-2 row justify-content-center">
        <div class="col-md-10">
            <textarea id="shop-description" placeholder="Shop description" class="form-control" required>{{$shop->description}}</textarea>
        </div>
    </div>
    <div class="mt-2 row justify-content-center">
        <div class="col-md-10">
            <div class="input-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="edit-shop-img">
                    <label class="custom-file-label" for="add-shop-img">Shop image</label>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-2 row justify-content-center">
        <div class="col-md-10">
            <img id="to-crop-image-shop" src="" alt="">
        </div>
    </div>
    <div class="mt-2 row justify-content-center">
        <div class="col-md-10">
            <img data-changed="0" style="width:100%;" id="shop-croped-image" src="/images/shops/{{$shop->img}}" alt="">
        </div>
    </div>
    <div class="mt-2 row justify-content-center">
        <div class="col-md-10">
            <button type="submit" class="btn btn-success btn-block">Add</button>
        </div>
    </div>
</form>
@endsection

resources/views/admin/shop-management/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <h3 class="text-dark m-0">
            Shops managment<i class="fas fa-store ml-1"></i>
        </h3>
    </div>
    <div class="col-md-4">
        <button class="btn btn-primary float-right" data-toggle="modal" data-target="#add-shop-modal"><i
                class="fas fa-plus mr-2"></i>Add shop</button>

        <div class="modal fade" id="add-shop-modal" tabindex="-1" role="dialog" aria-labelledby="add-shop-modal-label"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="add-shop-modal-label">Add shop</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="add-shop-form" data-url="{{route("admin-shop.store")}}">
                            <div class="row justify-content-center">
                                <div class="col-md-10">
                                    <input id="shop-name" placeholder="Shop name" type="text" class="form-control"
                                        required>
                                </div>
                            </div>
                            <div class="mt-2 row justify-content-center">
                                <div class="col-md-10">
                                    <input id="shop-email" placeholder="Shop email" type="email" class="form-control"
                                        required>
                                </div>
                            </div>
                            <div class="mt-2 row justify-content-center">
                                <div class="col-md-10">
                                    <input id="shop-phone" placeholder="Shop phone" type="text" class="form-control"
                                        required>
                                </div>
                            </div>
                            <div class="mt-2 row justify-content-center">
                                <div class="col-md-10">
                                    <textarea id="shop-description" placeholder="Shop description" class="form-control"
                                        required></textarea>
                                </div>
                            </div>
                            <div class="mt-2 row justify-content-center">
                                <div class="col-md-10">
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="add-shop-img" required>
                                            <label class="custom-file-label" for="add-shop-img">Shop image</label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="mt-2 row justify-content-center">
                                <div class="col-md-10">
                                    <img id="to-crop-image-shop" src="" alt="">
                                </div>
                            </div>
                            <div class="mt-2 row justify-content-center">
                                <div class="col-md-10">
                                    <img style="width:100%;" id="shop-croped-image" src="" alt="">
                                </div>
                            </div>
                            <div class="mt-2 row justify-content-center">
                                <div class="col-md-10">
                                    <button type="submit" class="btn btn-success btn-block">Add</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="row">
    @foreach ($shops as $shop)
    <div class="mt-2 col-md-3">
        <div class="card">
            <a class="link" href="{{route('admin-shop.show',$shop->id)}}">
                <img src="images/shops/{{$shop->img}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="text-dark card-title">
                        {{$shop->name}}
                    </h5>
                </div>
                <ul class="text-dark list-group list-group-flush">
                    <li class="list-group-item">
                        {{$shop->email}}
                    </li>
                    <li class="list-group-item">
                        {{$shop->phone}}
                    </li>
                    <li class="list-group-item">
                        {{str_limit($shop->description, $limit = 30, $end = '...')}}
                    </li>
                </ul>
            </a>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <a href="{{route('admin-shop.edit',$shop->id)}}" class="btn btn-primary btn-block">Edit</a>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-danger btn-block" data-toggle="modal"
                            data-target="#delete-shop-modal">Delete</button>

                        <div class="modal fade" id="delete-shop-modal" tabindex="-1" role="dialog"
                            aria-labelledby="delete-shop-modal-label" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="delete-shop-modal-label">
                                            Are you sure that you want to delete this shop?
                                        </h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row justify-content-center">
                                            <div class="col-md-5">
                                                <button type="button" data-dismiss="modal" aria-label="Close"
                                                    class="btn btn-block btn-success">Cancel</button>
                                            </div>
                                            <div class="col-md-5">
                                                <button data-url="{{route('admin-shop.destroy',$shop->id)}}" class="delete-shop-btn btn btn-block btn-danger">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endsection

resources/views/admin/shop-management/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-5">
        <img style="width:100%;" src="/images/shops/{{$shop->img}}" alt="">
    </div>
    <div class="col-md-7">
        <div class="row">
            <div class="col-md-12">
                <h2>{{$shop->name}}</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="description">
                    {{$shop->description}}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <span class="monospaced">{{__('pagination.Phone')}}</span>
            </div>
            <div class="col-md-9">
                <p>{{$shop->phone}}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <span class="monospaced">{{__('pagination.Email')}}</span>
            </div>
            <div class="col-md-9">
                <p>{{$shop->email}}</p>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th colspan="6" class="p-0" scope="col">
                        <button class="btn btn-primary btn-block" data-toggle="modal"
                            data-target="#add-shop-member-modal"><i class="fas fa-plus"></i></button>

                        <div class="modal fade" id="add-shop-member-modal" tabindex="-1" role="dialog"
                            aria-labelledby="add-shop-member-modal-label" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="add-shop-member-modal-label">Add member</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form data-shop-id="{{$shop->id}}"
                                            data-url="{{route('admin-shop-members.store')}}" id="add-shop-member-form">
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <input placeholder="Member name" id="shop-member-name" type="text"
                                                        class="form-control">
                                                </div>
                                            </div>
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <input placeholder="Member email" id="shop-member-email" type="text"
                                                        class="form-control">
                                                </div>
                                            </div>
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <input placeholder="Member phone" id="shop-member-phone" type="text"
                                                        class="form-control">
                                                </div>
                                            </div>
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <select class="form-control" id="shop-member-role" required>
                                                        <option value="" selected disabled>Select member role</option>
                                                        @foreach ($roles as $role)
                                                        <option value="{{$role->id}}">{{$role->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <button class="btn btn-success btn-block">Add</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </th>
                </tr>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Role</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($shop->members as $member)
                <tr>
                    <td>{{$member->name}}</td>
                    <td>{{$member->email}}</td>
                    <td>{{$member->phone}}</td>
                    <td>{{$member->role->name}}</td>
                    <td>
                        <i class="fas fa-edit text-success link" data-toggle="modal"
                            data-target="#edit-member-modal-{{$member->id}}"></i>

                        <div class="modal fade" id="edit-member-modal-{{$member->id}}" tabindex="-1" role="dialog"
                            aria-labelledby="edit-member-modal-{{$member->id}}-label" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="edit-member-modal-{{$member->id}}-label">Edit member
                                            info</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form data-member-id="{{$member->id}}"
                                            data-url="{{route('admin-shop-members.update',$member->id)}}"
                                            class="edit-shop-member-form">
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <input value="{{$member->name}}" placeholder="Member name"
                                                        id="shop-member-name-{{$member->id}}" type="text"
                                                        class="form-control">
                                                </div>
                                            </div>
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <input value="{{$member->email}}" placeholder="Member email"
                                                        id="shop-member-email-{{$member->id}}" type="text"
                                                        class="form-control">
                                                </div>
                                            </div>
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <input value="{{$member->phone}}" placeholder="Member phone"
                                                        id="shop-member-phone-{{$member->id}}" type="text"
                                                        class="form-control">
                                                </div>
                                            </div>
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <select class="form-control" id="shop-member-role-{{$member->id}}">
                                                        @foreach ($roles as $role)
                                                        @if ($member->role->id==$role->id)
                                                        <option value="{{$role->id}}" selected>{{$role->name}}</option>
                                                        @endif
                                                        <option value="{{$role->id}}">{{$role->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="row mt-2 justify-content-center">
                                                <div class="col-md-10">
                                                    <button class="btn btn-success btn-block">Edit</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>
                        <i class="fas fa-trash-alt text-danger link" data-toggle="modal"
                            data-target="#delete-member-modal-{{$member->id}}"></i>

                        <div class="modal fade" id="delete-member-modal-{{$member->id}}" tabindex="-1" role="dialog"
                            aria-labelledby="delete-member-modal-{{$member->id}}-label" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="delete-member-modal-{{$member->id}}-label">
                                            Are you sure that you want to delete this type?
                                        </h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row justify-content-center">
                                            <div class="col-md-5">
                                                <button type="button" data-dismiss="modal" aria-label="Close"
                                                    class="btn btn-block btn-success">Cancel</button>
                                            </div>
                                            <div class="col-md-5">
                                                <button data-id="{{$member->id}}" data-url="{{route('admin-shop-members.destroy', $member->id)}}" class="delete-member-btn btn btn-block btn-danger">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                @endforeach

            </tbody>
        </table>
    </div>
</div>
@endsection