routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['role','share']], function(){
    
    Auth::routes(); 
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('admin-lang', 'Admin\LanguagesController');
    Route::resource('admin', 'Admin\AdminController');
    Route::resource('admin-langs', 'Admin\LangsController');
    Route::resource('admin-types', 'Admin\TypesController');
    Route::resource('admin-category', 'Admin\CategoriesController');
    Route::resource('admin-propriety', 'Admin\ProprietyController');
    Route::resource('admin-propriety-val', 'Admin\PropertyValController');
    Route::resource('admin-general-settings', 'Admin\GeneralSettingsController');
    Route::resource('admin-blog', 'Admin\BlogController');
    Route::resource('admin-shop', 'Admin\ShopsController');
    Route::resource('admin-shop-members', 'Admin\ShopMembersController');
    Route::resource('image/upload', 'Admin\ImagesUploadController');
    Route::resource('shop_admin', 'Shop\ShopAdminController');
    Route::resource('shop_admin_category', 'Shop\CategoryController');
    Route::resource('shop_admin_type', 'Shop\TypesController');
    Route::resource('shop_admin_property', 'Shop\PropertyController');
    Route::resource('shop_admin_property_val', 'Shop\PropertyValController');
    Route::resource('shop_admin_product', 'Shop\ProductController');

    
    
    Route::get('/getFilterResult/{lang?}', 'PagesController@getFilterResult')->name('getFilterResult');
    Route::get('/wishlistProduct/{lang?}', 'PagesController@wishlistProduct')->name('wishlistProduct');
    Route::get('/wishlist/{lang?}', 'PagesController@wishlist')->name('wishlist');
    Route::get('/product/{id}/{lang?}', 'PagesController@product')->name('product');
    Route::get('/post/{id}/{lang?}', 'PagesController@post')->name('post');
    Route::get('/posts/{lang?}', 'PagesController@posts')->name('posts');
    Route::get('/shops/{lang?}', 'PagesController@shops')->name('shops');
    Route::get('/shop/{id}/{lang?}', 'PagesController@shop')->name('shop');
    Route::get('/type/{id}/{lang?}', 'PagesController@type')->name('type');
    Route::get('/category/{id}/{lang?}', 'PagesController@category')->name('category');
    Route::get('/categories/{lang?}', 'PagesController@categories')->name('categories');
    Route::get('/contact/{lang?}', 'PagesController@contact')->name('contact');
    Route::get('/services/{lang?}', 'PagesController@services')->name('services');
    Route::get('/about/{lang?}', 'PagesController@about')->name('about');
    Route::get('/{lang?}', 'PagesController@wellcome')->name('wellcome');
});

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use File;
use Auth;
use App\Langs;
use App\BlogPosts;
use App\BlogPostsTrans;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $posts=BlogPosts::all();
        $langs = Langs::all();
        return view('admin.blog.index',compact('langs','posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id=BlogPosts::create([
            'user_id' => Auth::user()->id
        ])->id;


        
        $image = $request['img'];  
        $virgula=strrpos($image,',');
        $str=substr($image, 0,$virgula+1);
        $bara=strrpos($image,'image/');
        $punct=strrpos($image,';base64');
        $extension= substr($str, $bara+6,$punct-$bara-6);
        $image = str_replace('data:image/'.$extension.';base64,', '', $image);
        $image = str_replace(' ', '+', $image);

        $imageName = 'post-cover-img-'.$id.'.'.$extension;
        
        File::put('images/cover/'. $imageName, base64_decode($image));

        BlogPosts::where('id',$id)->update([
            "img" => $imageName
        ]);
        
        foreach(json_decode($request['postTrans'],true) as $postTitle){
            BlogPostsTrans::create([
                'title' => $postTitle['title'],
                'description' => $postTitle['description'],
                'post_id' => $id,
                'lang_id' => $postTitle['langId']
            ]);

        }
        // /Applications/XAMPP/xamppfiles/htdocs/egros/resources/views/admin/general-settings/components/blog/new-post-form.blade.php
      
        return $id;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = BlogPosts::find($id);
        return view('admin.blog.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = BlogPosts::find($id);
        return view('admin.blog.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request['imgChanged']==1){
            $image = $request['img'];  
            $virgula=strrpos($image,',');
            $str=substr($image, 0,$virgula+1);
            $bara=strrpos($image,'image/');
            $punct=strrpos($image,';base64');
            $extension= substr($str, $bara+6,$punct-$bara-6);
            $image = str_replace('data:image/'.$extension.';base64,', '', $image);
            $image = str_replace(' ', '+', $image);

            $imageName = 'post-cover-img-'.$id.'.'.$extension;
            
            File::put('images/cover/'. $imageName, base64_decode($image));

            BlogPosts::where('id',$id)->update([
                "img" => $imageName
            ]);
        }
        
        foreach(json_decode($request['postTrans'],true) as $postTitle){
            BlogPostsTrans::where('id',$postTitle['postId'])->update([
                'title' => $postTitle['title'],
                'description' => $postTitle['description'],
            ]);
        }
     
        return route('admin-blog.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        BlogPosts::where('id',$id)->delete();
        return $id;
    }
}

resources/views/admin/blog/edit.blade.php
@extends('layouts.admin')

@section('content')
<form id="edit-blog-post-form" data-url="{{route('admin-blog.update',$post->id)}}">
    <div class="row justify-content-center mb-2">
        <div class="col-md-10">
            <div class="custom-file">
                <input type="file" name="cover_post" class="custom-file-input" id="edit-post-img">
                <label class="custom-file-label" for="edit-post-img">Choose image</label>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mb-2">
        <div class="col-md-10">
            <img style="width:100%;" src="" id="croped-image" alt="">
        </div>
    </div>

    <div class="row justify-content-center mb-2">
        <div class="col-md-10">
            <img data-changed="0" style="width:100%;" src="/images/cover/{{$post->img}}" id="croped" alt="">
        </div>
    </div>

    @foreach ($langs as $i=>$lang)
    @if($i==0)
    <hr>
    @endif
    <div class="row justify-content-center mb-2">
        <div class="col-md-10">
            <input value="{{$post->postTrans($lang->system_name)['title']}}" placeholder="{{$lang->name}}"
                id="edit-post-name-trans-{{$lang->id}}" type="text" class="form-control">
        </div>
    </div>
    <div class="row justify-content-center mb-2">
        <div class="col-md-10">
            <textarea name="content" data-post-id="{{$post->postTrans($lang->system_name)['id']}}"
                data-lang-id="{{$lang->id}}" class="edit-post-description-trans"
                id="editor-{{$i}}">{!!$post->postTrans($lang->system_name)['description']!!}</textarea>
        </div>
    </div>
    <hr>
    @endforeach

    <div class="row justify-content-center">
        <div class="col-md-10">
            <button type="submit" class="btn btn-success btn-block"><i class="far fa-save mr-2"></i>Save</button>
        </div>
    </div>
</form>
@endsection

resources/views/admin/blog/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-6">
        <h3 class="text-dark m-0">
            <i class="far fa-newspaper mr-2"></i>
            {{-- Blog --}}
            {{ __('auth.failed')}}
        </h3>
    </div>
    <div class="col-md-6">
        <button class="btn btn-primary float-right" data-toggle="modal" data-target="#add-post-modal"><i
                class="fas fa-plus mr-2"></i>Add post</button>

        <div class="modal fade" id="add-post-modal" tabindex="-1" role="dialog" aria-labelledby="add-post-modal-label"
            aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="add-post-modal-label">Add post</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="add-blog-post-form" data-url="{{route('admin-blog.store')}}">
                            <div class="row justify-content-center mb-2">
                                <div class="col-md-10">
                                    <div class="custom-file">
                                        <input type="file" name="cover_post" class="custom-file-input"
                                            id="add-post-img">
                                        <label class="custom-file-label" for="add-post-img">Choose image</label>
                                    </div>
                                </div>
                            </div>

                            <div class="row justify-content-center mb-2">
                                <div class="col-md-10">
                                    <img style="width:100%;" src="" id="croped-image" alt="">
                                </div>
                            </div>

                            <div class="row justify-content-center mb-2">
                                <div class="col-md-10">
                                    <img style="width:100%;" src="" id="croped" alt="">
                                </div>
                            </div>

                            @foreach ($langs as $i=>$lang)
                            @if($i==0)
                            <hr>
                            @endif
                            <div class="row justify-content-center mb-2">
                                <div class="col-md-10">
                                    <input placeholder="{{$lang->name}}" id="add-post-name-trans-{{$lang->id}}"
                                        type="text" class="form-control">
                                </div>
                            </div>
                            <div class="row justify-content-center mb-2">
                                <div class="col-md-10">
                                    <textarea name="content" data-lang-id="{{$lang->id}}"
                                        class="add-post-description-trans" id="editor-{{$i}}"></textarea>
                                </div>
                            </div>
                            <hr>
                            @endforeach

                            <div class="row justify-content-center">
                                <div class="col-md-10">
                                    <button type="submit" class="btn btn-success btn-block">Add</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<hr>

<div class="row">
    @foreach ($posts as $post)
    <div class="col-md-6">
        <div class="card mb-4">
            <a class="link text-dark" href="{{route('admin-blog.show',$post->id)}}">
                <img class="card-img-top" src="/images/cover/{{$post->img}}" alt="Card image cap">
            </a>
            <div class="pt-1 card-body text-center">
                <a class="link text-dark" href="{{route('admin-blog.show',$post->id)}}">

                    <h2 class="card-title">{{$post->postTrans(Auth::user()->default_lang)['title']}}</h2>
                    <p class="card-text">
                        {!! str_limit(strip_tags($post->postTrans(Auth::user()->default_lang)['description']), $limit =
                        65, $end = '...')!!}
                    </p>
                </a>
                <div class="mt-3 row">
                    <div class="col-md-6">
                        <a href="{{route('admin-blog.edit',$post->id)}}" class="btn btn-primary btn-block">
                                <i class="fas fa-edit mr-2"></i>Edit
                        </a>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-danger btn-block" data-toggle="modal" data-target="#delete-post-modal">
                                <i class="fas fa-trash-alt mr-2"></i>Delete
                        </button>

                        <div class="modal fade" id="delete-post-modal" tabindex="-1" role="dialog"
                            aria-labelledby="delete-post-modal-label" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="delete-post-modal-label">Are you sure that you
                                            want to delete this post?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row justify-content-center">
                                            <div class="col-md-5">
                                                <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-block btn-success">Cancel</button>
                                            </div>
                                            <div class="col-md-5">
                                                <button data-id="{{$post->id}}" data-url="{{route('admin-blog.destroy',$post->id)}}" class="delete-post-btn btn btn-block btn-danger">
                                                    Delete
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    @endforeach
</div>


@endsection

resources/views/admin/blog/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-lg-8">
        <h1 class="mt-4">
            {{$post->postTrans(Auth::user()->default_lang)['title']}}
        </h1>
        <p class="lead">
            by {{$post->user->name}}
        </p>
        <hr>
        <p>
            Posted on {{date_format($post->created_at, 'd.m.y , g:i a')}}
        </p>
        <hr>
        <img style="width:100%" class="img-fluid rounded" src="/images/cover/{{$post->img}}" alt="">
        <hr>
        {!! $post->postTrans(Auth::user()->default_lang)['description']!!}
        <hr>
    </div>
    <div class="col-md-4">
        <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-secondary" type="button">Go!</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection